{
  "agents": [
    {
      "id": "slot01",
      "slot": "01",
      "role": "router",
      "approach": "diagnostic-routing",
      "model": "default",
      "description": "Diagnose intent and route; ask clarifying questions when context is missing.",
      "params": { "temperature": 0.2, "top_p": 0.9, "max_tokens": 256 }
    },
    {
      "id": "slot02",
      "slot": "02",
      "role": "reasoner",
      "approach": "deep-reason",
      "model": "default",
      "description": "Structured reasoning and trade-offs; prepare assumptions and acceptance criteria.",
      "params": { "temperature": 0.1, "top_p": 0.9, "max_tokens": 512 }
    },
    {
      "id": "slot03",
      "slot": "03",
      "role": "planner",
      "approach": "plan-steps",
      "model": "default",
      "description": "Plan minimal verifiable steps and validation checkpoints.",
      "params": { "temperature": 0.1, "top_p": 0.9, "max_tokens": 512 }
    },
    {
      "id": "slot04",
      "slot": "04",
      "role": "fast_action",
      "approach": "quick-fix",
      "model": "default",
      "description": "Small, safe changes (<10 lines); prioritize speed and low risk.",
      "params": { "temperature": 0.3, "top_p": 0.9, "max_tokens": 128 }
    },
    {
      "id": "slot05",
      "slot": "05",
      "role": "retriever",
      "approach": "memory-bridge",
      "model": "default",
      "description": "Orchestrate memory.search (HTTP/MCP) calls and assemble context.",
      "params": { "temperature": 0.2, "top_p": 0.9, "max_tokens": 256 }
    },
    {
      "id": "slot06",
      "slot": "06",
      "role": "verifier",
      "approach": "fast-verify",
      "model": "default",
      "description": "Lightweight verification: logical linting, diff review, and quick checks.",
      "params": { "temperature": 0.0, "top_p": 0.9, "max_tokens": 128 }
    },
    {
      "id": "slot08",
      "slot": "08",
      "role": "coder",
      "approach": "implement-safe",
      "model": "default",
      "description": "Implement focused changes, following repo style and limits.",
      "params": { "temperature": 0.2, "top_p": 0.9, "max_tokens": 512 }
    },
    {
      "id": "slot09",
      "slot": "09",
      "role": "debugger",
      "approach": "failure-analysis",
      "model": "default",
      "description": "Analyze failures/logs, minimize repro steps, and propose fixes.",
      "params": { "temperature": 0.2, "top_p": 0.9, "max_tokens": 512 }
    },
    {
      "id": "slot10",
      "slot": "10",
      "role": "finalizer",
      "approach": "summarize-handoff",
      "model": "default",
      "description": "Close tasks with summary, changes, and next steps.",
      "params": { "temperature": 0.1, "top_p": 0.9, "max_tokens": 256 }
    }
  ]
}
