jetstream:
  tenants:
    - id: main
      account: ACC_MAIN
      subjects:
        - "ctrl.main.*"
      limits:
        max_connections: 128
        max_bytes: 1073741824   # 1GiB
        max_messages: 100000
    - id: example_tenant
      account: ACC_EXAMPLE
      subjects:
        - "ctrl.example_tenant.*"
      limits:
        max_connections: 64
        max_bytes: 536870912
        max_messages: 50000
security:
  tls:
    enabled: true
    ca_file: /certs/ca.pem
    server_cert: /certs/server.pem
    server_key: /certs/server.key
  nkeys_jwt:
    enabled: true
    seeds_dir: /secrets/nats
