defaults:
  partitions_per_active_model: 3-6   # dev-friendly; scale by tenant x model
  compression: zstd
  producer:
    linger_ms: 15           # small batching latency for throughput
    batch_size: 131072      # 128KB
    acks: all               # idempotent producers recommended
  retention:
    time: 48h
    size: 16GiB
  dlq:
    enabled: true
    suffix: dlq
  retry:
    enabled: true
    suffix: retry

topics:
  - name: "llm.<tenant>.infer.requests.v1"
    partitions: 6
    config:
      compression.type: zstd
      retention.ms: 172800000
  - name: "llm.<tenant>.infer.results.v1"
    partitions: 6
    config:
      compression.type: zstd
  - name: "llm.<tenant>.embeddings.ingest.v1"
    partitions: 3
    config:
      compression.type: zstd
  - name: "llm.<tenant>.mem.events.v1"
    partitions: 3
    config:
      compression.type: zstd
  - name: "llm.<tenant>.retry.infer.v1"
    partitions: 3
  - name: "llm.<tenant>.dlq.infer.v1"
    partitions: 3

security:
  sasl_scram:
    enabled: true
    users:
      - username: tenant_writer
        password: "<REDACTED>"
      - username: tenant_reader
        password: "<REDACTED>"
  tls:
    enabled: true
    ca_file: "/certs/ca.pem"
    server_cert: "/certs/server.pem"
    server_key: "/certs/server.key"
